Repository w3c/webdriver-bidi, pull requests merged in 2022-10, with the labels that each got.

#153 Add a context parameter for browsingContext.create
  index.bs
Labels: enhancement, browsingContext

#290 MapRemoteValue/SetRemoteValue optional value
  index.bs
Labels: bug, remote value

#310 Fix indentation for browsingContext.create
  index.bs
Labels: bug, browsingContext
