Repository w3c/webdriver-bidi, pull requests merged in 2024-11, with the labels that each got.

#812 Make sure --upgrade results in a pip --upgrade
  scripts/build.sh
Labels: bug, infra

#814 Fix the ordering of steps in serialize as a remote value
  index.bs
Labels: bug, remote value

#819 Update Bikeshed metadata: add editors, TR link, drop level
  index.bs
Labels: infra, blocked
