Repository w3c/webdriver-bidi, pull requests merged in 2025-01, with the labels that each got.

#811 Extend locateNodes with a locator to get navigable's container element
  index.bs
Labels: needs-tests

#854 Always include stacktrace for console messages
  index.bs
Labels: needs-tests

#836 Introduce user context subscriptions
  index.bs
Labels: needs-tests

#864 Fix build errors
  index.bs
Labels: bug, infra

#863 Prevent navigable being overridden by parent navigable
  index.bs
Labels: bug, module-browsingContext

#871 Fix webExtension.install base64 parameter name
  index.bs
Labels: bug, module-webExtension

#855 Add browsingContext.navigationCommitted event and wait for it when no wait condition is provided
  index.bs
Labels: needs-tests
